export const SET_USER = "SET_USER";
export const SET_UNAUTHENTICATED = "SET_UNAUTHENTICATED";
export const CHANGE_PICTURE = "CHANGE_PICTURE";
export const SET_AUTHENTICATED = "SET_AUTHENTICATED";
export const SET_GROUPS = "SET_GROUPS";
export const CREATE_GROUP = "CREATE_GROUP";
export const SET_CURRENT_GROUP = "SET_CURRENT_GROUP";
